# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: native_imaging
version: 0.2.0
description: Dart bindings for Imaging from Pillow with jpeg and blurhash encoders
homepage: https://github.com/famedly/dart_native_imaging
repository: https://github.com/famedly/dart_native_imaging/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  js: ^0.7.2
  ffi: ^2.1.4

dev_dependencies:
  test: ^1.9.0
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_imaging
        pluginClass: NativeImagingPlugin
      ios:
        pluginClass: NativeImagingPlugin
